use_frameworks!

target 'custom-ui_Example' do
  pod 'custom-ui', :path => '../'
  target 'custom-ui_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
